version: "3.8"

services:
  db:
    image: postgis/postgis:15-3.3 # PostgreSQL 15 + PostGIS 3.3 조합
    container_name: park_gis_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER} # .env 파일에서 로드
      POSTGRES_PASSWORD: ${DB_PASSWORD} # .env 파일에서 로드
      POSTGRES_DB: park_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # 데이터 영구 저장
    networks:
      - park_network

networks:
  park_network:
    driver: bridge
